### ISSUE TITLE
Checkpoint 1

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [GlynisF/EventVisualizer2#3]
Hi @GlynisF - I am creating a separate issue for the checkpoint to keep this feedback separate from the week 5 hibernate work. 

**Problem statement** 

Does an excellent job clearly explaining the problem and the solution. Good use of images to convey the story.  When your project is complete, I'd recommend updating the readme with a short video or screenshots of your application. This is going to be really cool when it's done! 

**User stories w/ MVP stories identified** Your users stories are clear and well-written following the best practices for user stories. They clearly communicate what your application will do. Your MVP stories seem to include what's needed for the ent java project requirements like crud.

- [ ] I am not sure if the stories represent multiple one to many relationships.

- [ ] I see reference to notebooks in your screens, but did not see a user story for this. How do notebooks fit in? How and where are they accessed. What do they do?

**Wireframes**. Good work on these! The wireframes clearly communicate what each page will do and seem to match up with the user stories above, with the exception of the notebook question.

**Project Plan** A good start with tasks planned through this week (week 7)!

- [ ] I recommend at least identifying which user story you plan to work on each week.  Chatgpt can be helpful brainstorming tasks if you are having trouble coming up with them. I think the more detailed you can be the better. What do you think about creating a task for each story to decide which jsp/s, controllers, entities, tables you'll need for that story.  Revising the plan could be a task on the plan itself (woah!). It's time to detail what you are going to do for the second half of the semester! This should be completed for check point 2 which is due Wed.

**Reflection/Time log** Keep up the good work with this. 

**********
checkpoint 1 : met
